// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:99e9189f-cc95-407b-bd34-081172dbcd20",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_b4UtHLi3f",
    "aws_user_pools_web_client_id": "47cv53lfnq2nlv6dvfn9n9s2ue",
    "oauth": {},
    "aws_mobile_analytics_app_id": "09610c1f1e1545848a8aa41190ac9539",
    "aws_mobile_analytics_app_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://kiogdlchqjczjg3xywmndapnda.appsync-api.ap-northeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
